# Generated by Django 2.2.1 on 2019-05-28 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='configuration',
        ),
        migrations.AddField(
            model_name='group',
            name='analysis_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_analysis_configuration', to='app.Configuration'),
        ),
        migrations.AddField(
            model_name='group',
            name='prediction_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_prediction_configuration', to='app.Configuration'),
        ),
        migrations.AddField(
            model_name='profile',
            name='analysis_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_configuration', to='app.Configuration'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prediction_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_configuration', to='app.Configuration'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_clouds',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_humidity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_pm1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_pm10',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_pm25',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_pressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_temp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_wind',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='period',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
