# Generated by Django 2.2.1 on 2019-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190528_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='period',
            field=models.CharField(max_length=4),
        ),
    ]
