# Generated by Django 2.2.1 on 2019-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190718_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
